services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      UID: 3004
      GID: 3004
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/DUNE/configs/minecraft:/data