services:
  proxy-manager:
    container_name: proxy-manager
    image: 'jc21/nginx-proxy-manager:2.12.3'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - /mnt/DUNE/configs/proxymanager:/data
      - /mnt/DUNE/configs/letsencrypt:/etc/letsencrypt
    
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M