services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: 'America/Toronto'
      WATCHTOWER_NOTIFICATION_URL: ${DISCORD_WEBHOOK}
      WATCHTOWER_NOTIFICATION_TEMPLATE: "{{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}"
      WATCHTOWER_SCHEDULE: "0 1 * * *"